name: CI

on:
  push:
    branches:
      - main
  pull_request:
      - main

jobs:
  Style:
    uses: ./.github/workflows/check-whitespace.yml
  Substance:
    uses: ./.github/workflows/build.yml
    needs: Style
